module Parseg
  class Change
    # A range of the change
    #
    # ```rb
    # 1...3
    # 1...1
    # ```
    attr_reader range: Range[Integer]

    # The updated text
    attr_reader text: String

    def initialize: (Range[Integer] range, String text) -> void

    # Applies the changes to the `source`
    #
    # * First change comes first in the array
    # * Returns a pair of resulting string and concatenated range
    #
    def self.apply: (String source, Array[Change] changes) -> [String, Range[Integer]]
  end
end
