module Parseg
  class Grammar
    module Expression
      type t = TokenSymbol
             | NonTerminalSymbol
             | Alternation
             | Repeat
             | Optional
             | Empty

      interface _Expression
        %a{pure} def next_expr: () -> t?

        def my_first_tokens: () -> Set[Symbol | nil]

        # Set of tokens that can be used to construct a tree that corresponds to the expression
        #
        def consumable_tokens: () -> Set[Symbol]
      end

      module FirstTokensUtil : _Expression
        def first_tokens: () -> Set[Symbol | nil]
      end

      class TokenSymbol
        attr_reader token: Symbol

        attr_reader next_expr: t?

        include FirstTokensUtil

        def initialize: (Symbol, ?next_expr: t?) -> void

        def my_first_tokens: () -> Set[Symbol | nil]

        def +: (t) -> TokenSymbol

        def consumable_tokens: () -> Set[Symbol]
      end

      class NonTerminalSymbol
        include FirstTokensUtil

        attr_reader non_terminal: NonTerminal

        attr_reader next_expr: t?

        def initialize: (NonTerminal, ?next_expr: t?) -> void

        def my_first_tokens: () -> Set[Symbol | nil]

        def +: (t) -> NonTerminalSymbol

        def consumable_tokens: () -> Set[Symbol]
      end

      class Empty
        include FirstTokensUtil

        attr_reader next_expr: t?

        def +: (t) -> t

        @@instance: Empty
        def self.instance: () -> Empty

        def my_first_tokens: () -> Set[Symbol | nil]

        def consumable_tokens: () -> Set[Symbol]
      end

      class Alternation
        include FirstTokensUtil

        attr_reader expressions: Array[t]

        attr_reader next_expr: t?

        def initialize: (*t, ?next_expr: t?) -> void

        def my_first_tokens: () -> Set[Symbol | nil]

        def +: (t) -> Alternation

        def consumable_tokens: () -> Set[Symbol]
      end

      class Repeat
        include FirstTokensUtil

        attr_reader content: t
        attr_reader separator: t

        attr_reader next_expr: t?

        def initialize: (content: t, separator: t, ?next_expr: t?) -> void

        def my_first_tokens: () -> Set[Symbol | nil]

        def +: (t) -> Repeat

        def consumable_tokens: () -> Set[Symbol]
      end

      class Optional
        include FirstTokensUtil

        attr_reader expression: t

        attr_reader next_expr: t?

        def initialize: (t, ?next_expr: t?) -> void

        def my_first_tokens: () -> Set[Symbol | nil]

        def +: (t) -> Optional

        def consumable_tokens: () -> Set[Symbol]
      end
    end

    class NonTerminal
      attr_accessor rule: Expression::t

      attr_reader name: Symbol

      def initialize: (Symbol) -> void

      %a{pure} def closing_token: () -> Expression::TokenSymbol?

      def block?: () -> bool
      @block: bool

      def block!: () -> self
    end

    interface _WithGrammar
      def grammar: () -> Grammar
    end

    module DSL : _WithGrammar
      # Defines a terminal symbol with token type in Symbol.
      #
      def T: (Symbol) -> Expression::TokenSymbol

      # Defines a non-terminal symbol with non-terminal name in Symbol.
      #
      def NT: (Symbol) -> Expression::NonTerminalSymbol

      # Optional tree that is the expression or empty.
      #
      def Opt: (Expression::t) -> Expression::Optional

      # Repeat tree represents a repeat of a tree, with optional separator.
      #
      # At least one `content` tree is required.
      # Use it with `Opt` to accept empty repeatation.
      #
      def Repeat: (Expression::t, ?Expression::t) -> Expression::Repeat

      # Alternation tree represents one of the given trees.
      #
      def Alt: (*Expression::t) -> Expression::Alternation

      # Empty tree consumes no token.
      # 
      def Empty: () -> Expression::Empty
    end

    attr_reader non_terminals: Hash[Symbol, NonTerminal]

    def initialize: (*Symbol) ?{ (Grammar) [self: DSL] -> void } -> void

    def []: (Symbol) -> NonTerminal
  end
end
