use RBS::Buffer
use LanguageServer::Protocol::Interface::*

module Parseg
  class LspTreeFormatter
    attr_reader factory: TokenFactory

    attr_reader buffer: Buffer

    module LSP = LanguageServer::Protocol

    def initialize: (TokenFactory, Buffer) -> void

    def format_tree: (Tree::tree, last_position: LanguageServer::Protocol::position) -> Array[DocumentSymbol]
  end
end
