module Parseg
  class StrscanTokenizer
    include _Tokenizer

    attr_reader tokens: Hash[Symbol, Regexp]

    attr_reader skips: Regexp

    def initialize: (Hash[Symbol, Regexp] tokens, Regexp skips) -> void
  end
end
