module Parseg
  interface _Tokenizer
    # Yields a tuple of token type, start position, and the value String from given `source`
    #
    # Yields `nil` if there are no more tokens left in the input.
    #
    def each_token: (String source) { (token?) -> void } -> void
  end
end
